// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMHeRwya8gQiK7-5u1557chofAv-gZTWk',
    appId: '1:732203376303:web:2e9d521838826762cafe5a',
    messagingSenderId: '732203376303',
    projectId: 'smart-kuehlschrank81',
    authDomain: 'smart-kuehlschrank81.firebaseapp.com',
    storageBucket: 'smart-kuehlschrank81.firebasestorage.app',
    measurementId: 'G-2N3M2213JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMeejRb1Vz8weXXY7xIJcdpz5hRFThJSg',
    appId: '1:732203376303:android:ef29af1a6cfd9520cafe5a',
    messagingSenderId: '732203376303',
    projectId: 'smart-kuehlschrank81',
    storageBucket: 'smart-kuehlschrank81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7telQUVQdpQPyhqdj-jRMPjcn1QaFreQ',
    appId: '1:732203376303:ios:aa967cbdd06b8ac0cafe5a',
    messagingSenderId: '732203376303',
    projectId: 'smart-kuehlschrank81',
    storageBucket: 'smart-kuehlschrank81.firebasestorage.app',
    iosBundleId: 'com.example.projekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7telQUVQdpQPyhqdj-jRMPjcn1QaFreQ',
    appId: '1:732203376303:ios:aa967cbdd06b8ac0cafe5a',
    messagingSenderId: '732203376303',
    projectId: 'smart-kuehlschrank81',
    storageBucket: 'smart-kuehlschrank81.firebasestorage.app',
    iosBundleId: 'com.example.projekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMHeRwya8gQiK7-5u1557chofAv-gZTWk',
    appId: '1:732203376303:web:ed5ad5c42e5d6481cafe5a',
    messagingSenderId: '732203376303',
    projectId: 'smart-kuehlschrank81',
    authDomain: 'smart-kuehlschrank81.firebaseapp.com',
    storageBucket: 'smart-kuehlschrank81.firebasestorage.app',
    measurementId: 'G-NT7M96D29K',
  );

}