import 'package:flutter/material.dart';

// --- Firebase Imports ---
import 'package:firebase_core/firebase_core.dart';
import 'package:projekt/widgets/auth_gate.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
// --- Firebase Imports ---

import 'screens/home_screen.dart';
// Corrected import path to the newly created screen
import 'screens/shopping_list_screen.dart'; 
import 'screens/notifications.dart';
import 'screens/account.dart';

// Updated main function to initialize Firebase
Future<void> main() async { 
  // Ensure that Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized(); 

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Run the app through the AuthGate
  runApp(const MyApp());
}

// The root widget of the application.
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Smarter Kühlschrank',
      theme: ThemeData(
        primarySwatch: Colors.teal,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const AuthGate(), // Start with the authentication gate
    );
  }
}

// The main app screen with the bottom navigation bar.
// This is shown after a user is successfully logged in.
class MainAppScreen extends StatefulWidget {
  const MainAppScreen({super.key});

  @override
  State<MainAppScreen> createState() => _MainAppScreenState();
}

class _MainAppScreenState extends State<MainAppScreen> {
  int _selectedIndex = 0;

  static const List<Widget> _screens = [
    HomeScreen(),
    ShoppingListScreen(),
    NotificationsScreen(),
    AccountScreen(),
  ];

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: _screens[_selectedIndex],
        bottomNavigationBar: BottomNavigationBar(
          currentIndex: _selectedIndex,
          onTap: _onItemTapped,
          selectedItemColor: Colors.teal,
          unselectedItemColor: Colors.grey,
          items: const [
            BottomNavigationBarItem(
              icon: Icon(Icons.kitchen),
              label: 'Startseite',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.shopping_cart),
              label: 'Einkaufen',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.notifications),
              label: 'Benachrichtigungen',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.account_circle),
              label: 'Konto',
            ),
          ],
        ),
      );
  }
}
